# Use root/example as user/password credentials
version: '3.8'

services:

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: jamalstore_db
      MYSQL_USER: jamalstore
      MYSQL_PASSWORD: jamalstore

      MYSQL_ROOT_PASSWORD: root